version: "3.8"
services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: backend
    environment:
      - APP_URL=${APP_URL}
      - APP_NAME=${APP_NAME}
      - APP_KEY=${APP_KEY}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=dev
      - APP_DEBUG=true
    restart: always
    volumes:
      - ./backend:/var/www
      - .:/workspace:cached
      - /var/www/vendor
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/app
      - .:/workspace:cached
      - /app/node_modules
  proxy:
    build:
      context: ./proxy/local
      dockerfile: Dockerfile
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/local:/etc/nginx/conf.d
